### PR TITLE
connected two diff id's

### PR DESCRIPTION
**Pull request by Perumallpardhiv**
image

connecting recyclerview top to my_img bottom

### CODE REVIEW

**Comment by Perumallpardhiv** [comment]
@Rohit1173 sir once check this

**Comment by Rohit1173** [comment]
@Perumallpardhiv remove the `layout_marginTop` of TextView ,So that it would be in the middle of the image and update your screenshot accordingly.

**Comment by Perumallpardhiv** [comment]
> @Perumallpardhiv remove the `layout_marginTop` of TextView ,So that it would be in the middle of the image and update your screenshot accordingly.

image

@Rohit1173  Is this the u said sir?

**Comment by Rohit1173** [comment]
> > @Perumallpardhiv remove the `layout_marginTop` of TextView ,So that it would be in the middle of the image and update your screenshot accordingly.
> 
> image
> 
> @Rohit1173 Is this the u said sir?

yes . Push that changes too.

**Comment by Rohit1173** [comment]
LGTM,Thanks!

**Pull request merged**
