### PR TITLE
Solves #1 Issue

### PR DESCRIPTION
**Pull request by superiorsd10**
Issue #1 

I have used string resources from strings.xml in activity_main.xml & activity_main.xml (land).

Screenshot_28
Screenshot_29

### CODE REVIEW

**Comment by Rohit1173** [comment]
@superiorsd10 Update your pr with screenshots of the UI of `activity_main.xml` & `activity_main.xml (land)`

**Comment by superiorsd10** [comment]
@Rohit1173 Sir, I have updated the PR with the screenshots.

**Comment by Rohit1173** [comment]
@superiorsd10 I have asked you to update the PR with screenshots after your code changes are made, but you have updated with screenshots before the changes are made.

**Comment by superiorsd10** [comment]
I have updated @Rohit1173 Sir! Sorry for that mistake.

**Comment by Rohit1173** [comment]
@superiorsd10, as you have seen the views, are not arranged properly in the images you have on your pr. This is because you have used `@string` resource on things like `parent`, `wrap_content`..etc.
You shouldn't use `@string` resource for these things . `@string` should be used only for harcoded texts present in the file.
You could take reference from [this](https://github.com/ayush0402/tic-tac-toe-foss/pull/32) pr.

**Comment by superiorsd10** [comment]
@Rohit1173 Sir Thanks for guiding me through this. I'm closing this PR, and will create a new PR for this issue.

**Pull request closed without merging**
